Dojo = [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'X                                                                                                                           X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]
#
